import { namespaceActions } from 'modules/redux-utils'
import { NAME } from './constants'

const LOAD_GROUP_LIST = 'LOAD_GROUP_LIST'
const ADD_GROUP = 'ADD_GROUP'
const UPDATE_GROUP = 'UPDATE_GROUP'
const DELETE_GROUP = 'DELETE_GROUP'
const REMOVE_USER_FROM_GROUP = 'REMOVE_USER_FROM_GROUP'
const ADD_USER_TO_GROUPS = 'ADD_USER_TO_GROUPS'
const REMOVE_USER_FROM_ALL_GROUPS = 'REMOVE_USER_FROM_ALL_GROUPS'

export default namespaceActions(NAME)([
  LOAD_GROUP_LIST,
  ADD_GROUP,
  UPDATE_GROUP,
  DELETE_GROUP,
  REMOVE_USER_FROM_GROUP,
  ADD_USER_TO_GROUPS,
  REMOVE_USER_FROM_ALL_GROUPS
])
