import { namespaceActions } from 'modules/redux-utils'
import { NAME } from './constants'

const LOAD_SHEET = 'LOAD_SHEET'
const UPDATE_SHEET = 'UPDATE_SHEET'
const SET_CURRENT_SHEET = 'SET_CURRENT_SHEET'
const TOGGLE_RECORD_ATTACHMENTS = 'TOGGLE_RECORD_ATTACHMENTS'
const SHOW_CREATE_SHEET_MODAL = 'SHOW_CREATE_SHEET_MODAL'
const HIDE_CREATE_SHEET_MODAL = 'HIDE_CREATE_SHEET_MODAL'
const ADD_SHEET = 'ADD_SHEET'
const CREATE_FIELD = 'CREATE_FIELD'
const UPDATE_FIELD = 'UPDATE_FIELD'
const DELETE_FIELD = 'DELETE_FIELD'
const ADD_FIELD_NEW_SHEET = 'ADD_FIELD_NEW_SHEET'
const RESET_FIELD_COUNT = 'RESET_FIELD_COUNT'

export default namespaceActions(NAME)([
  LOAD_SHEET,
  UPDATE_SHEET,
  ADD_SHEET,
  SET_CURRENT_SHEET,
  TOGGLE_RECORD_ATTACHMENTS,
  SHOW_CREATE_SHEET_MODAL,
  HIDE_CREATE_SHEET_MODAL,
  CREATE_FIELD,
  UPDATE_FIELD,
  DELETE_FIELD,
  ADD_FIELD_NEW_SHEET,
  RESET_FIELD_COUNT
])
