import { namespaceActions } from 'modules/redux-utils'
import { NAME } from './constants'

const HIDE_USER_MODAL = 'HIDE_USER_MODAL'
const SHOW_USER_MODAL = 'SHOW_USER_MODAL'
const RESET_PASSWORD_PROCESSING = 'RESET_PASSWORD_PROCESSING'
const RESET_PASSWORD_COMPLETE = 'RESET_PASSWORD_COMPLETE'

const HIDE_CREATE_USER_MODAL = 'HIDE_CREATE_USER_MODAL'
const SHOW_CREATE_USER_MODAL = 'SHOW_CREATE_USER_MODAL'

const SEND_INVITE_PROCESSING = 'SEND_INVITE_PROCESSING'
const SEND_INVITE_COMPLETE = 'SEND_INVITE_COMPLETE'

const CHANGING_USER_ACTIVE_STATUS_USER = 'CHANGING_USER_ACTIVE_STATUS_USER'
const ACTIVATE_USER = 'ACTIVATE_USER'
const DEACTIVATE_USER = 'DEACTIVATE_USER'

const HIDE_DELETE_USER_MODAL = 'HIDE_DELETE_USER_MODAL'
const SHOW_DELETE_USER_MODAL = 'SHOW_DELETE_USER_MODAL'

const TOGGLE_FILTERS = 'TOGGLE_FILTERS'

const CHANGE_USER_IMAGE = 'CHANGE_USER_IMAGE'

export default namespaceActions(NAME)([
  HIDE_USER_MODAL,
  SHOW_USER_MODAL,
  RESET_PASSWORD_PROCESSING,
  RESET_PASSWORD_COMPLETE,

  SEND_INVITE_PROCESSING,
  SEND_INVITE_COMPLETE,

  CHANGING_USER_ACTIVE_STATUS_USER,
  ACTIVATE_USER,
  DEACTIVATE_USER,

  HIDE_CREATE_USER_MODAL,
  SHOW_CREATE_USER_MODAL,

  HIDE_DELETE_USER_MODAL,
  SHOW_DELETE_USER_MODAL,

  TOGGLE_FILTERS,

  CHANGE_USER_IMAGE
])
